CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Surname NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    FatherName NVARCHAR(100) NULL,
    Address NVARCHAR(255) NULL,
    MobilePhone NVARCHAR(20) NULL,
    CardNumber NVARCHAR(50) NULL,
    TableNumber NVARCHAR(50) NULL,
    Birthdate DATETIME NULL,
    DateOfEmployment DATETIME NULL,
    DateOfDismissal DATETIME NULL,
    Note NVARCHAR(MAX) NULL,
    Gender INT NOT NULL,  
    UserType INT NOT NULL,
    UpdatedBy   INT            NULL,
    CreatedBy   INT            NULL,
    DeletedBy   INT            NULL,
    CreatedDate DATETIME2 (7)  NULL,
    DeletedDate DATETIME2 (7)  NULL,
    UpdatedDate DATETIME2 (7)  NULL,
    IsDeleted   BIT            NOT NULL DEFAULT 0
);
